### ISSUE TITLE
Feature request: automatically replace texas ops with unicode equivalents

### ISSUE THREAD

**Issue by AlexDaniel** [vim-perl/vim-perl6#8]
This ticket is inspired by [reddit comments](https://www.reddit.com/r/perl/duplicates/6v8eop/201734_going/).

Example: you type ``<=``, it should automatically replaces it with ``≤``. Obviously, make it possible to turn that feature off, but perhaps consider having it enabled by default.

List of non-texas ops: https://docs.perl6.org/language/unicode_texas

Sister tickets:
* [atom-language-perl6](https://github.com/perl6/atom-language-perl6/issues/72)
* [perl6-mode](https://github.com/perl6/perl6-mode/issues/14)

**Comment by hoelzro** [comment]
I think this is a good idea, and would accept a PR implementing this; you could accomplish this like so:

```vim

if get(g:, 'perl6_mess_with_texas')
  inoremap <= ≤
endif
```

**Comment by mickk-on-cpp** [comment]
```vimL
iabbrev <buffer> / ÷
```

I believe this interacts poorly with a couple of things, e.g.:

- with a `/`-delimited regex: `$haystack ~~ / pattern /;` → `$haystack ~~ ÷ pattern ÷;`, affects substitutions/transliterations as well
- with infix `//`: `say $this // $that;` → `say $this ÷/ $that;`

**Comment by AlexDaniel** [comment]
@mickk-on-cpp does it perform the replacement automatically on the whole document? I thought you'd have to explicitly tell it to do the substitution at cursor. And if so, it's not a problem if it replaces wrong stuff?

**Comment by mickk-on-cpp** [comment]
> does it perform the replacement automatically on the whole document? I thought you'd have to explicitly tell it to do the substitution at cursor.

The abbreviation system does take place on input and is not a global substitution, but it is implicit and not explicit. The examples I gave illustrate what happens when writing e.g. a `/`-delimited regex: the delimiters get turned into division signs (the first one when inputting the following space, the second one when inputting the semicolon).

> And if so, it's not a problem if it replaces wrong stuff?

The crux of the issue is that if the user is more likely to use `/` for non-division purposes, then the abbreviation runs counter to its purpose: it's neither convenient nor time-saving. Of course the user can choose to remove it on their installation, but I believe there’s a precedent where e.g. plus and minus abbreviations were removed for being disruptive as well.

**Comment by AlexDaniel** [comment]
I see.

**Comment by Tyil** [comment]
@mickk-on-cpp That is correct, I did disable the `+` and `-` earlier on for being more often wrong than not. I have been considering to do the same for `/` and `*` as these are commonly going wrong for me too. I do like the `×` variant as well, so maybe I'll look to see if I can get `*` to only transform into `×` if it's directly followed by a space.
